// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA868bRwPZfKAGpR6gC_1vvdF0n_taiJ5g',
    appId: '1:527202980450:web:816f06f8d2724e5d80373b',
    messagingSenderId: '527202980450',
    projectId: 'fashionapp-110311',
    authDomain: 'fashionapp-110311.firebaseapp.com',
    storageBucket: 'fashionapp-110311.appspot.com',
    measurementId: 'G-CZWLMWPQJ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzsRAh-i5q7jxQ0hZTROayj_aCHCr0CSQ',
    appId: '1:527202980450:android:2bcb9c56425a2a8380373b',
    messagingSenderId: '527202980450',
    projectId: 'fashionapp-110311',
    storageBucket: 'fashionapp-110311.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWVG5oIYaZDp6BBGuIHZUkynt2fminZYg',
    appId: '1:527202980450:ios:b0c1aa276ad2b34d80373b',
    messagingSenderId: '527202980450',
    projectId: 'fashionapp-110311',
    storageBucket: 'fashionapp-110311.appspot.com',
    iosBundleId: 'com.example.fashionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWVG5oIYaZDp6BBGuIHZUkynt2fminZYg',
    appId: '1:527202980450:ios:053deef8b1fcd78580373b',
    messagingSenderId: '527202980450',
    projectId: 'fashionapp-110311',
    storageBucket: 'fashionapp-110311.appspot.com',
    iosBundleId: 'com.example.fashionApp.RunnerTests',
  );
}
